language: node_js
node_js:
- '0.12'
after_success:
- npm run build
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/darlingjs/bower-darlingjs.git
  - secure: HKKhepZ7ZWa0xZQQTBAzdugMmFE9MtTwJhaOllcfTeZwc8B2OFtV7qVtnaK3xP1VZud78jGJ+hQ8rAeJFqR0xkbosqFVvbf1FBd2czV4s9LZz8ZyqVMM940b9Wmd4b4ySsjtayBbfH8CcBem9EF1VoQBU3WXrDuGgODQU77fIls=
